Master
Simpit-team/KerbalSimpitRevamped-Arduino pull request #2
Opened 2020-11-10 09:56 UTC by PBechon

Implement feature for #1 and for a feature request on the C# repository (that was not opened on the right repository) https://github.com/LRTNZ/KerbalSimpitRevamped/issues/3

The idea is to add a throttleMessage struct to more easily send throttle message and to add an example to show how to control throttle or rotation.

2020-11-15 10:47 UTC, LRTNZ commented
Just to clarify before merging this in - this is all working fine?

2020-11-15 12:39 UTC, PBechon commented
Yes, I tested it on a Arduino uno with a single potentiometer that I sequetially plug in each of the 3 input pin used as I did not have enough potentiometers ;)

2020-11-15 12:40 UTC, LRTNZ requested changes

2020-11-15 12:40 UTC, LRTNZ commented on src/PayloadStructs.h
> +    This struct contains information about wheel steering and throttle. */
Wheel Steering? The struct only has throttle information in it?

2020-11-15 12:40 UTC, LRTNZ commented on examples/KerbalSimpitThrottleDemo/KerbalSimpitThrottleDemo.ino
> +   Assume A0, A1, A2 are plugged on a potentiometer
Could you please include a link to a well documented resource (Sparkfun, Arduino, Adafruit), that shows how to do this, to help people new to Arduinos and electronics in general.

2020-11-15 12:40 UTC, LRTNZ commented on examples/KerbalSimpitThrottleDemo/KerbalSimpitThrottleDemo.ino
> +  rot_msg.roll = map(reading_roll, 0, 1023, INT16_MIN, INT16_MAX);
Example of deadzone?

2020-11-15 19:41 UTC, PBechon commented on src/PayloadStructs.h
> +    This struct contains information about wheel steering and throttle. */
Fixed, it was a copy-pasted that did not apply here.

2020-11-15 19:41 UTC, PBechon commented on examples/KerbalSimpitThrottleDemo/KerbalSimpitThrottleDemo.ino
> +   Assume A0, A1, A2 are plugged on a potentiometer
I added two links and improved the description

2020-11-15 19:42 UTC, PBechon commented on examples/KerbalSimpitThrottleDemo/KerbalSimpitThrottleDemo.ino
> +  rot_msg.roll = map(reading_roll, 0, 1023, INT16_MIN, INT16_MAX);
I did not find clean code for deadzone, I think it is better to keep the example simple enough. I removed the mention of deadzone.

2020-11-16 04:02 UTC, LRTNZ commented on examples/KerbalSimpitThrottleDemo/KerbalSimpitThrottleDemo.ino
> +  rot_msg.roll = map(reading_roll, 0, 1023, INT16_MIN, INT16_MAX);
Sweet!

2020-11-16 04:05 UTC, LRTNZ approved these changes

2020-11-16 04:06 UTC, merged